// <auto-generated />
namespace dbPersistance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class itemThree : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(itemThree));
        
        string IMigrationMetadata.Id
        {
            get { return "202002150930078_itemThree"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
